### ISSUE TITLE
Liquibase / FlyWay for SQL migration scripts management

### ISSUE THREAD

**Issue by birdayz** [elysium-project/database#1]
Hi,

are these the real scripts used for Elysium? If yes, are how are they applied to the testing/production environments? On my job i've worked alot with DB migrations and used tools to keep track of datamodel versions etc. I hope you don't apply SQL scripts "by hand", which is very error prone.
I would suggest migration tools like Liquibase or FlyWay to ease versionization of the data model and master data (e.g. items etc). These tools also make it easier and more reliable to apply SQL migrations to production databases.

Regards,
birdy

**Comment by shenna-elysium** [comment]
Hi!
We use migration system for the main 1.12 DB, but itemization patches are
real mess, I know.

I can tell you the backstory behind those pathces of you will probably
suggest how to handle it the right way :) My Discord: Shenna#5640

**Comment by q409192015** [comment]
Hello, I would like to ask you to open source it? Why haven't you seen the core code yet? Your private community building is really great! I'm your player and I'm a programmer for 6 years. I hope to learn some experience through your core.

**Comment by shenna-elysium** [comment]
We're going open source, sure. The core is almost ready for publishing :)

**Comment by Kittnz** [comment]
Good to know @shenna-elysium thanks for the efford from you guys! Keep it up.

**Comment by Cylae** [comment]
@shenna-elysium Hey world database will be released too ?

**Comment by Kittnz** [comment]
@Cylae why wouldn't it?

**Comment by Cylae** [comment]
@Kittnz Dunno, i'm just asking 😄

**Comment by shenna-elysium** [comment]
Yes, sure.

**Comment by woiwoz** [comment]
This is very good, I represent the world of Warcraft players to pay tribute to you, I am willing to do a volunteer to do some technical aspects of things. Repair bug

**Comment by martinjlowm** [comment]
Seems like this issue has gone a bit off topic. Regardless, I agree with the structure of these SQL files and Flyway seems like a good solution to make changes in terms of migrations.

@birdayz, as I think you have more experience in DB migrations than I do, what do you think about my proposal of a migration structure?:

```
sql/
  1.02/
    1.02__enchants.sql
    1.02__game_events.sql
    1.02__items.sql
    1.02__npcs.sql
    1.02__area_triggers.sql

  1.03/
    # same structure as above
    
  1.05/
    ...
    
  1.06/
    ...
    
  1.07/
    ...
    
  1.08/
    ...
    
  1.09/
    ...
    
  1.10/
    ...
    
  1.12/
    ...
```
From a quick look at Flyway, it seems like it should be able to process subdirectories and perform the migrations, in order, listed from the earliest patch (1.02) to 1.12.

**Comment by birdayz** [comment]
I have talked to Shenna yesterday, and she explained me the issues with these migrations.
The situation, as i understood, is the following:

The Baseline Dataset is on patch 1.12 state. 
Each of the existing files "downgrades" the 1.12 World DB to a specific patch, e.g. 1.2

Since there is one file for each patch, there is ALOT of duplication, since the downgrade to 1.2 contains many downgrades for 1.9 for example.

Additionally, when for example a server is upgraded from 1.2 to 1.4, the whole world db is dropped, fresh 1.12 data is imported and downgraded again, but to 1.4 this time.

So, i can see (with my very limited insight into the project) two issues:

1) Duplication
2) Dropping+Downgrading World DB for every (major?) patch, instead of migrating forward, may be retarded.

For the moment i would like to focus on 1). 2) is retarded, but i think it's not that bad since it can be done in a "clean" and reliable way (which is deterministic).

Regarding 1), i think Liquibase might be the better choice. FlyWay is lightweight, but less powerful when it comes to the orchestration of "shared" logic. 

My current thoughts:

sql/
 items/
  downgrade_to_pre_1.10_gear.sql
  downgrade_t1_to_pre_1.X.sql
  downgrade_epic_pvp.sql
....
 npc/
 patch_1.2.0.xml
 patch_1.4.0.xml

Each of the xml configs defines what has to be done to migrate to a certain patchlevel. Since the actual migrations are only defined once, there is no duplication.

Example how such an entry in the xml config could look like:
```
<changeSet author="birdy" id="bonereavers_1">
    <sqlFile dbms="mysql"
            encoding="utf8"
            endDelimiter="\nGO"
            path="items/downgrade_bonereavers_edge.sql"
            relativeToChangelogFile="true"
            splitStatements="true"
            stripComments="true"/>
</changeSet>
```

Well this is still somewhat cumbersome due to 2), because we have to think backwards and migrate from the "end state" to an earlier state. I wonder, if it is feasible to define a new baseline dump/sql script which creates a 1.2 (earliest patch we care about?) world DB. This would allow us to migrate forward, which would be desirable.
I would love to get some feedback on my thoughts.

**Comment by Kittnz** [comment]
Can you follow your thoughts. You already said it, it's **reliable**. And it gives you a full last patch working database. Spawns and such can be done thru game_events but not the item and spell changes.

It's not like there are really MAJOR changes tho in each patch because most of the time everything is already in the full database. It's not that a bad idea to scratch what does not fit and change what needs to but you have to document everything clearly.

**Comment by shenna-elysium** [comment]
@martinjlowm Nice. I think we should start unfucking itemization with your idea. First and foremost, I need to sort out the gathered data the well structured way. It will take a week, If I am lucky.

**Comment by shenna-elysium** [comment]
@birdayz Moving forward isn't possible. Unfortunatelly, it's hard to handle everything in one patcher, also not possible to downgrade DB to the earlied version and bring it back to the latest one. Theoretically, it is, but it would take tons of time and human resources. Keep in mind, we are still in lack of information about each patch itemization. For Elysium developers it's much easier to work with full 1.12 databasse and downgraid it with a proper patcher to the version we need.

**Comment by shenna-elysium** [comment]
@birdayz 
> Each of the xml configs defines what has to be done to migrate to a certain patchlevel. Since the actual migrations are only defined once, there is no duplication.

This is a dream :(

**Comment by AndersSahlin** [comment]
If we are able to create a baseline of the DB for each patch by downgrading wouldn't it be quite easy to create upgrade (patch) scripts from diffing two baselines? 

1.12 -> downgrade script for 1.2 -> 1.2 baseline
1.12 -> downgrade script for 1.3 -> 1.3 baseline 

1.3 baseline  -> diff 1.2 baseline -> patch script
