### ISSUE TITLE
Some locales tables Spanish Languages are empty

### ISSUE THREAD

**Issue by Locario** [elysium-project/database#1]
Hi all.

All this tables are populated with language support. Chinese, French, Russian, etc, the next tables are locales empty in Spanish Language:

locales_points_of_interest
locales_page_text
locales_npc_text
locales_gossip_menu_option
locales_area

Would be nice knows if this titanic work done was for Elysium or Nostalrius, i tried to traslate from French with Babylon but most texts looses the real meaning, if almost i would have English texts pehaps can do another try.

**Comment by Locario** [comment]
Ok i have English texts, will try to traslate it but peharps you will see a pull request in many months!!!!

**Comment by m-laniakea** [comment]
Yes, we don't have many spanish translations. They exist... somewhere.

**Comment by Locario** [comment]
This is for MaNGOS R2, but they can be merged into a Elysium Database

https://github.com/Mrbytes/EsWoW2_MaNGOSR2/tree/master/mangosR2

LOTS of esES content
