### ISSUE TITLE
Darrowshire Patch 1.7 Darkmoon Neckpieces Should be Upgraded to Epic

### ISSUE THREAD

**Issue by albino-gryphon** [elysium-project/database#15]
Added as blue/rare in 1.6, both neck pieces were upgraded to epic with 1.7, but this has not come to pass on Darrowshire yet.

Amulet of the Darkmoon should now be Epic with 10 str, 19 agl, 10 stm
http://db.vanillagaming.org/?item=19491

Orb of the Darkmoon should now be Epic with 11 stm, 8 spr, +22 dmg/heal
http://db.vanillagaming.org/?item=19426

**Comment by AnikusTheRed** [comment]
Still not fixed :(

**Comment by m-laniakea** [comment]
That's nothing. [This](https://github.com/elysium-project/server/issues/87) guy has been waiting more than two months. 
The correct values are already there, but it may take a while for them to be applied to the server. Have some patience, please.
