### ISSUE TITLE
Carapace Spine Crossbow missing in 1.4/1.5

### ISSUE THREAD

**Issue by martinjlowm** [elysium-project/database#26]
This crossbow is currently missing in the 1.4/1.5 upgrade/downgrade script. Comment timestamps in [1] show evidence of it being added to the game in 1.4.

[1] http://web.archive.org/web/20050514143356/http://wow.allakhazam.com:80/db/item.html?witem=18738

Would have done a pull request, but the new patching scheme seems scary.

**Comment by thepparker** [comment]
I can confirm that Carapace Spine Crossbow is definitely in and does drop

**Comment by martinjlowm** [comment]
It cannot be queried on Elysium.

**Comment by thepparker** [comment]
Sorry, I meant in the current iteration of this repository. As in, it will be dropping once the patch to fix the patch is applied
