### ISSUE TITLE
Flarecore Leggings stats in 1.6

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/database#31]
In Patch 1.6, Flarecore Leggings should have +53 fire damage instead of +43 spell power.

### Sources:

https://web.archive.org/web/20051210133306/http://www.thottbot.com/?i=40679

8th comment down:
>"The +53 Dmg gives its full benefit to 3 second and longer spells"

http://wowwiki.wikia.com/wiki/Flarecore_Leggings

>Patch 1.6.0 (12-Jul-2005): Added.
>Patch 1.7.0 (13-Sep-2005): Flarecore Leggings now provide a damage bonus to all spells, not just fire spells.

**Comment by thepparker** [comment]
Marked for 1.6 itemization

**Comment by Sabre142** [comment]
@thepparker 

It might also be worth noting, for the sake of continuity, that the same thing also happened to Flarecore Robes.

You can see the old stats on both items here:

https://web.archive.org/web/20050901172512/http://www.thottbot.com:80/?i=26657 (scroll down to tailoring and hover over the items.) 53 fire damage on pants, 29 fire damage on robe.

Finally, it seems Flarecore Gloves are BoP in 1.6 til 1.7. I don't know how dedicated the team is to care about this though.

https://web.archive.org/web/20050425211034/http://www.thottbot.com:80/?i=26592

Patch 1.7 notes: Flarecore Gloves now bind when equipped.

**Comment by Sabre142** [comment]
Closing as it was fixed, thank you
