### ISSUE TITLE
Missing migrations from the new World DB

### ISSUE THREAD

**Issue by brotalnia** [elysium-project/database#38]
This new world db https://github.com/elysium-project/database/blob/master/full_db/world_1.12_20170607064011.7z is missing many migrations, even before 20170607064011.

Here is a list of all missing entries in the migrations table.

> 20170515222637
> 20170516221623
> 20170517055715
> 20170517172339
> 20170518014257
> 20170518024209
> 20170518175736
> 20170518211554
> 20170518222031
> 20170518223007
> 20170519115936
> 20170519154718
> 20170519183313
> 20170521020215
> 20170521091910
> 20170522102813
> 20170522105340
> 20170523171301
> 20170524133211
> 20170524223357
> 20170525000721
> 20170526010757
> 20170526172341
> 20170526191229
> 20170526192823
> 20170526195701
> 20170527165904
> 20170527192151
> 20170527222317
> 20170528133059
> 20170530185638
> 20170531142831
> 20170601002619
> 20170601215440
> 20170601221758
> 20170602212240
> 20170603185948
> 20170604041201
> 20170604165032
> 20170605141221
> 20170607011915
> 20170607150514
> 20170607215004
> 20170608143646
> 20170608213734
> 20170609001236
> 20170609115510
> 20170609224735
> 20170611155039
> 20170614040115
> 20170615070657
> 20170615091820
> 20170617085959
> 20170620074952
> 20170621100208
> 20170621131230
> 20170626192443
> 20170628103600
> 20170629002825
> 20170629130810
> 20170630151500
> 20170630160000
> 20170630201907
> 20170701193000
> 20170707183148
> 20170707202843
> 20170708231555

**Comment by shenna-elysium** [comment]
Wrong branch 🙄 This revision is currently running on Anathema, but with 1.10 downgrading patch. I'll upload a clean one for developers later. Sorry.
