### ISSUE TITLE
Mark Turn In Quests

### ISSUE THREAD

**Issue by Dalark** [elysium-project/database#40]
The quests are not available to do and i'm loosing my marks saved in the mail, help.

**Comment by darbai** [comment]
I am also having the issues of Mark of Honor hand in quests not showing up/existing. My character level is 39 if there is any level specific issues.

**Comment by Frapee** [comment]
Yes please fix this issue, this is especially a critical issue because rankers rely on the marks of last week and due to the pvp changes they will start dissappearing soon!
