### ISSUE TITLE
Claw of the Black Drake missing Crit

### ISSUE THREAD

**Issue by kschroeder31** [elysium-project/database#47]
It should have 1 crit

http://db.vanillagaming.org/?item=19365
http://wowwiki.wikia.com/wiki/Claw_of_the_Black_Drake Doesn't show any changes in the patch history

I can't find anything anywhere that it was buffed to include the 1% crit later.

**Comment by BrynjaDarrow** [comment]
He is right. It should have 1% crit from the start.

Proof:
http://i.imgur.com/1NosAWp.jpg

**Comment by kschroeder31** [comment]
It currently doesn't have the crit on Elysium server. I haven't checked the others.

**Comment by brotalnia** [comment]
The critical strike chance is showing fine on the default database.

**Comment by zelazrgn** [comment]
Can you check/apply a hotfix to the Elysium database?

**Comment by precisionn** [comment]
Hey can we get this fixed please! 1% crit is a massive stat to lose in a BWL raid

**Comment by thepparker** [comment]
Itemization will be improved significantly with the next content updates (very soon), and issues like this can be resolved much easier (and will hopefully be avoided entirely). Until then, we won't be hotfixing any items.
