### ISSUE TITLE
Plan: Titanic Leggings not dropping on Anathema

### ISSUE THREAD

**Issue by mumblesmcgee** [elysium-project/database#49]
I hope this is the right spot for this and apologise if it is not. In short, the plans for titanic leggings did not drop after patch 1.10 was released. This was confirmed to be an issue and a fix for this was supposed to go out in a recent update but it appears to not have changed anything as the plans still don't appear to drop. Please rescue all the poor fury warriors who have been waiting for so long for this!

**Comment by JosipbrozElysium** [comment]
They are dropping now!

Best regards!
