### ISSUE TITLE
Warlock Tier 2 Nemesis Belt, Boots and Robes have wrong ( still 1.3 patch) stats on Elysium

### ISSUE THREAD

**Issue by Hegelol** [elysium-project/database#54]
Nemesis Belt, Nemesis Boots and Nemesis Robes have not been upgraded to patch 1.6 stats. However, all of the other pieces have been upgraded. Here is what these items need to look like in patch 1.6:

http://web.archive.org/web/20051211002606/http://wow.allakhazam.com/db/itemset.html?setid=212

For reference here is a history of the Warlock Tier 2 armor upgrades per patch:

Stats for 1.9 are as follows:
http://web.archive.org/web/20060215115018/http://wow.allakhazam.com/db/itemset.html?setid=212

Stats for 1.6 are as follows:
http://web.archive.org/web/20051211002606/http://wow.allakhazam.com/db/itemset.html?setid=212

Stats for 1.3 are as follows:
http://web.archive.org/web/20050620074053/http://wow.allakhazam.com/db/itemset.html?setid=212

**Comment by shenna-elysium** [comment]
Fixed, thanks.
