### ISSUE TITLE
Paladin + Naretzek,blood drinker 

### ISSUE THREAD

**Issue by Fnt** [elysium-project/database#56]
Bugged life steal proc 
![bug](https://user-images.githubusercontent.com/2942240/28748573-1f14a6cc-74f6-11e7-96d9-5f56dbb38621.jpg)

**Comment by Fnt** [comment]
![bug2](https://user-images.githubusercontent.com/2942240/28748593-9955358c-74f6-11e7-96ba-94cc2465975d.jpg)

**Comment by Xaph-er** [comment]
Its supposed to scale 100% with spell power.

**Comment by Fnt** [comment]
And has a 90 chance? For 10 simple strokes of 9 procs, too fat.

**Comment by Xaph-er** [comment]
Where's the screenshot of it proccing every swing?

**Comment by Itembugs** [comment]
It doesnt proc alot.

It procs every maybe 20 normal swings

Or every 10 with seal

**Comment by thepparker** [comment]
I believe this was changed in a recent PR
