### ISSUE TITLE
Acidic Walkers Have Wrong Stats

### ISSUE THREAD

**Issue by Brunheda** [elysium-project/database#58]
I'm pretty sure that in this patch Acidic Walkers had different stats. The current item is 4 Agility, 8 Intellect, 7 Spirit, 5 Nature Resistance. It should be:

8 Intellect
4 Spirit
5 Nature Resistance
Equip: Increases spell power by 5.

**Comment by Kolmarwow** [comment]
"In patch 1.10 they changed the stats. The old stats were +8 int, +4 agi, +7 spi, +5 nature resist. So they got rid of the +4 agi and took 3 spi, and replaced them with +5 spell. "

https://web.archive.org/web/20061231221943/http://wow.allakhazam.com:80/item.html?witem=9454

So if you are playing on Anathema then yes they have the wrong stats and should be fixed, if you are playing on Darrowshire or Elysium then it's working as intended.

**Comment by Brunheda** [comment]
Thanks, my bad. Didn't even know we were pre patch 1.10.
