### ISSUE TITLE
Zandalarian Hero Charm pre-1.11 effect

### ISSUE THREAD

**Issue by Sabre142** [elysium-project/database#65]
As Patch 1.11 notes:

> The damage and healing on this item have been reduced by 30%. Instead of granting 35 damage and 70 healing per charge, it now grants 25 damage and 50 healing per charge. http://wowwiki.wikia.com/wiki/Zandalarian_Hero_Charm

Old version of ZHC: http://web.archive.org/web/20060410193831/http://wow.allakhazam.com:80/db/item.html?witem=19950

Patch 1.11 version (the current one on all realms): http://db.vanillagaming.org/?item=19950

I was wondering if the old effect of this trinket could be recreated.

**Comment by brotalnia** [comment]
It can be recreated using the `spell_effect_mod` table, but the tooltip on the client would still be wrong, as the spell description is not sent by the server, it is contained in the client files, which would confuse players. I think there is a decision not to change spell specific stuff for this reason (on equip, on hit, on use item effects are spells).
