### ISSUE TITLE
Empty IN() clause produces MySQL error

### ISSUE THREAD

**Issue by henkethebenke** [elysium-project/database#66]
[These lines](https://github.com/elysium-project/database/blob/master/progression/1.3%20%E2%86%92%201.4%20The%20Call%20to%20War.sql#L29-L30) produces MySQL error `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1`.

I guess you are generating the query using a program. You should change that program so that it does not write anything if the IN() clause is empty.

**Comment by shenna-elysium** [comment]
Well, I plan to fill it with the right values in the next days :) Those patches aren't ready to go in work yet!

**Comment by shenna-elysium** [comment]
No special program there; anyway, queries to _loot tables gonna be handled on the core/config soon. We're doing the research for now.

**Comment by henkethebenke** [comment]
Ok, thanks! Looking forward to use it for my project when it's done :blush:
