### ISSUE TITLE
Wrath of cenarius should work on every hit of aoe in 1.11

### ISSUE THREAD

**Issue by Itembugs** [elysium-project/database#75]
Wrath of cenarius ticks on every tick of aoe in 1.11 (consecration etc)
and every tick of channelled spells in 1.12 (arcane missiles)
And affect ALL damaging spells in 1.11

At the moment its not on anathema

It should work on every hit from consecration since 
Consecration is aoe and doesnt do a debuff like DoT.

elysium-project/server#420

guybrushgit comment

How it currently works: (wrong)
Direct damage: procs once. 
Damage over time: procs once.  
Channeled direct damage (Arcane Missiles): procs once.
AoE: doesnt proc.

How it should work: (right)
Direct damage: procs once. (judgement, shadowbolt etc)
Damage over time: Most sources say only procs once. (CoA/corruption/venomhide poison etc)
Channeled direct damage: procs on every hit. (arcane missiles)
AoE: From the sources it seems this was initially bugged and didnt proc but it was later fixed to proc on every single hit. (consecration)

Reading material:
http://db.vanillagaming.org/?item=21190#wh-comments
https://web.archive.org/web/20070906075803/http://thottbot.com/i21190
https://web.archive.org/web/20070313104450/http://wow.allakhazam.com/db/item.html?witem=21190
http://wowwiki.wikia.com/wiki/Patch_1.10.0
http://wowwiki.wikia.com/wiki/Patch_1.12.0
http://wowdata.buffed.de/item/Ruestung/Verschiedenes/Zorn-des-Cenarius-21190#comments

--

**Comment by Itembugs** [comment]
Wrath of cenarius ticks on every tick of aoe in 1.12

It should work on every hit from consecration since
Consecration is aoe and doesnt do a debuff like DoT.

Wrath of cenarius should work once on ticks

It should work on everybarcane missile or chanelled spell

Please fix

Please see guybushgit comment for fix. Ty

https://github.com/elysium-project/server/issues/420

**Comment by Itembugs** [comment]
Please see guybushgit comment for fix. Ty

elysium-project/server#420

**Comment by Itembugs** [comment]
Please see guybushgit comment for fix. Ty

elysium-project/server#420



Reading material:
http://db.vanillagaming.org/?item=21190#wh-comments
https://web.archive.org/web/20070906075803/http://thottbot.com/i21190
https://web.archive.org/web/20070313104450/http://wow.allakhazam.com/db/item.html?witem=21190
http://wowwiki.wikia.com/wiki/Patch_1.10.0
http://wowwiki.wikia.com/wiki/Patch_1.12.0
http://wowdata.buffed.de/item/Ruestung/Verschiedenes/Zorn-des-Cenarius-21190#comments

**Comment by Itembugs** [comment]
Its working fine on DoTs and direct single spells

1. Its not affecting all damage spells like shadow oil or venomhide poison

2. Its not working in every aoe hit

3. Its not working on every channelled hit

**Comment by Itembugs** [comment]
Its working fine on DoTs and direct single spells

Its not affecting all damage spells like shadow oil or venomhide poison DoT

Its not working in every aoe hit

Its not working on every channelled hit

**Comment by Itembugs** [comment]
Its working fine on DoTs and direct single spells

1. Its not affecting all damage spells like shadow oil or venomhide poison DoT

2. Its not working in every aoe hit

3. Its not working on every channelled hit

**Comment by thepparker** [comment]
Wrong repository, also a duplicate
