### ISSUE TITLE
Important Issue

### ISSUE THREAD

**Issue by Unholny** [elysium-project/database#77]
Hello everyone.

I am a long-term TrinityCore developer but now I decided to give mangos zero a try.

Unfortunately I am having problems with the map extractors..
I tried to use those on mangos website and used the client that is given in the elysium-project website and it gives me the following error:

Data/maps/0004331.map is non-compatible version (outdated?). Please, create new using ad.exe program.

I didn't see a folder with "tools" but I saw the extractors folder in contrib. Unfortunately during installation, I marked the checkbox for Map Extractors but still I didn't get any extractors in the build folder. What's up?

**Comment by brotalnia** [comment]
You need to use the Giperion branch to compile extractors.

Or you can just download these for Windows:
https://github.com/elysium-project/server/files/852498/Elysium.Extractors.18.March.zip

**Comment by Unholny** [comment]
Thank you, brotalnia.

Can I ask you a personal question - are you from Bulgaria ? (your nickname means brutal in Bulgarian)

Can you share your skype details with me? I want to ask a few questions regarding emulation with mangos.

**Comment by brotalnia** [comment]
Да, ама аз в скайп не влизам вече, пиши ми в дискорд. Там съм brotalnia#0541.
