### ISSUE TITLE
All weapon oils from enchanting are 1.9 - including the one from ZG vendor

### ISSUE THREAD

**Issue by kev41** [elysium-project/database#82]
http://wowwiki.wikia.com/wiki/Formula:_Brilliant_Mana_Oil - Patch 1.9.0 (03-Jan-2006): Added.

http://wowwiki.wikia.com/wiki/Brilliant_Mana_Oil - Patch 1.9.0 (03-Jan-2006): Added.

http://wowwiki.wikia.com/wiki/Formula:_Brilliant_Wizard_Oil - Patch 1.9.0 (03-Jan-2006): Added.

http://wowwiki.wikia.com/wiki/Brilliant_Wizard_Oil - Patch 1.9.0 (03-Jan-2006): Added.

http://wowwiki.wikia.com/wiki/Formula:_Lesser_Mana_Oil - Patch 1.9.0 (03-Jan-2006): Added.

http://wowwiki.wikia.com/wiki/Lesser_Mana_Oil - Patch 1.9.0 (03-Jan-2006): Added.

http://web.archive.org/web/20060722033532/http://wow.allakhazam.com:80/item.html?witem=20744 - People started comment about it 2006 June.

http://web.archive.org/web/20060722033547/http://wow.allakhazam.com:80/item.html?witem=20745 - Added to their database 2006

http://web.archive.org/web/20060722033613/http://wow.allakhazam.com:80/item.html?witem=20750 - Alot of comments about this NEW Oil at January 2006 (1.9 Release)

http://web.archive.org/web/20060722033601/http://wow.allakhazam.com:80/item.html?witem=20749 - 2006 Januar (1.9) they find out about ZG oils and comments about it!

PATCH 1.9 CHANGE LOG: Enchanters can now turn some of their dusts and shards into magical oils. These oils when applied to weapons add a temporary bonus to magical damage or mana regeneration that stacks with permanent enchantments. The lower levels of these recipes are found on normal enchanting vendors. The higher level versions are found on special vendors and are rewards for high Zandalar faction.

ALL OILS, no matter if minor or brilliant came in 1.9 patch.

DO NOT launch ZG 1.7 with the oils you have in currently Elysium 1.7 REPO

Thanks

**Comment by thepparker** [comment]
We are aware of when they were added, they won't be available.
