### ISSUE TITLE
Witch Doctor Mau'ari should be in Orgrimmar on Eyslium-PVP

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/database#9]
@carn222
In the current patch on Elysium, Witch Doctor Mau'ari should be placed in Orgrimmar, rather than Everlook

https://web-beta.archive.org/web/20070815125842/http://wow.allakhazam.com:80/db/mob.html?wmob=10307

http://wowwiki.wikia.com/wiki/Patch_1.7.0

@martinjlowm 

Here's a (not very reliable) source stating her position to be (36,81): http://wow.gamepressure.com/npc.asp?ID=2419

**Comment by martinjlowm** [comment]
Assuming the position source is correct, I think this [1] would be the most obvious position that she would be standing, facing towards players walking across the rocks - and also without standing in their way.

[1] http://i.imgur.com/RcQpRid.png
